#ifndef _CONNECTION_STATUS_H
#define _CONNECTION_STATUS_H

typedef enum
{
    CONNECTION_STATUS_IDLE,
    CONNECTION_STATUS_SEARCHING,
    CONNECTION_STATUS_CHECK_SIGNAL,
    CONNECTION_STATUS_CONNECTING,
    CONNECTION_STATUS_CONNECTED,
}CONNECTION_STATUS;

#endif 